container:
  image: node:latest

test_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install
  test_script: yarn run test

check_task:
  check_script: cmp -s dist/x.js src/x.js